- name: add Elastic GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Configure Elastic repo
  copy:
    src: elastic.repo
    dest: /etc/yum.repos.d/

- name: Setup Logstash
  include_role:
    name: logstash

- name: Setup ElasticSearch
  include_role:
    name: elasticsearch

- name: Setup Kibana
  include_role:
    name: kibana
