- name: Install Kibana
  yum:
    name: kibana-6.0.1
    state: latest

- name: Create folder for Kibana log
  file:
    path: /var/log/kibana
    state: directory
    mode: 0777

- name: Create Kibana log
  file:
    path: /var/log/kibana/kibana.log
    state: touch
    mode: 0777

- name: Set Kibana logfile in configuration
  replace:
    path: /etc/kibana/kibana.yml
    regexp: "#logging.dest: stdout"
    replace: "logging.dest: /var/log/kibana/kibana.log"

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes
