- name: Install standard software for httpd
  yum:
    name: "{{ item }}"
  with_items:
    - httpd
    - libselinux-python
    - libsemanage-python

- name: Enable Apache HTTP Server
  service:
    name: httpd
    enabled: yes
    state: started

- name: Allow Apache HTTP Server to call back-end service
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Configure server name
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    line: 'ServerName test'
    insertafter: '^#\s?ServerName.*80$'

- name: Add configuration for site
  template:
    src: "test.conf"
    dest: "/etc/httpd/conf.d/"

- name: Reload Apache HTTP Server
  service:
    name: httpd
    state: reloaded
